# Generated by Django 5.1.6 on 2025-02-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonset3',
            name='types',
            field=models.JSONField(default=list),
        ),
    ]
