# Generated by Django 5.1.5 on 2025-02-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_id_user_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_id",
        ),
        migrations.AddField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
