# Generated by Django 5.1.5 on 2025-02-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PokemonSet4",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("supertype", models.CharField(max_length=100)),
                ("number", models.CharField(max_length=100)),
                ("rarity", models.CharField(max_length=100)),
                ("image", models.URLField(max_length=300)),
            ],
        ),
    ]
