# Generated by Django 5.1.5 on 2025-02-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_set', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=100)),
                ('printedTotal', models.IntegerField()),
                ('image', models.URLField(max_length=300)),
            ],
        ),
    ]
