# Generated by Django 5.1.5 on 2025-02-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonSet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonset',
            name='id_set',
        ),
        migrations.AlterField(
            model_name='pokemonset',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
