# Generated by Django 5.1.5 on 2025-02-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PokemonCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_card", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("image_url", models.URLField()),
                ("types", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
