# Generated by Django 5.1.5 on 2025-02-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_pokemoncard_rarity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemoncard',
            name='id',
        ),
        migrations.AlterField(
            model_name='pokemoncard',
            name='id_card',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
